{% set version = "0.4.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-echarts4r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/echarts4r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/echarts4r/echarts4r_{{ version }}.tar.gz
  sha256: 8284256e09a7239e0cff373cd22344130ee567db5639492b246fd92a903099f7

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  skip: true  # [r_base == "4.0"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom
    - r-corrplot
    - r-countrycode
    - r-d3r
    - r-data.tree
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr
    - r-purrr
    - r-scales
    - r-shiny
    - r-stringi
  run:
    - r-base
    - r-broom
    - r-corrplot
    - r-countrycode
    - r-d3r
    - r-data.tree
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr
    - r-purrr
    - r-scales
    - r-shiny
    - r-stringi

test:
  commands:
    - $R -e "library('echarts4r')"           # [not win]
    - "\"%R%\" -e \"library('echarts4r')\""  # [win]

about:
  home: http://echarts4r.john-coene.com/
  license: Apache-2.0
  summary: Easily create interactive charts by leveraging the 'Echarts Javascript' library which includes 34 chart types, themes, 'Shiny' proxies and animations.
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: echarts4r
# Title: Create Interactive Graphs with 'Echarts JavaScript' Version 4
# Date: 2019-07-15
# Version: 0.2.3
# Authors@R: person("John", "Coene", email = "jcoenep@gmail.com", role = c("aut", "cre"))
# Description: Easily create interactive charts by leveraging the 'Echarts Javascript' library which includes 34 chart types, themes, 'Shiny' proxies and animations.
# License: Apache License (>= 2.0)
# Encoding: UTF-8
# LazyData: true
# Imports: htmlwidgets, magrittr, dplyr, purrr, countrycode, d3r, broom, shiny, scales, corrplot, data.tree, htmltools, jsonlite, stringi
# Suggests: tidyr
# RoxygenNote: 6.1.1
# URL: http://echarts4r.john-coene.com/
# BugReports: https://github.com/JohnCoene/echarts4r/issues
# NeedsCompilation: no
# Packaged: 2019-07-16 14:49:45 UTC; jcoe
# Author: John Coene [aut, cre]
# Maintainer: John Coene <jcoenep@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-18 06:37:08 UTC
