appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Xio4hXdkaSHO1QaPzEmT5NQ4iM2f9viUxU0I2+kEgdglZpAddo6pDwy/vsKR6X2x2HA6NvaQ0u+x7d36OlSOxDWPBLRY49de20Ob1P6t/jFpgUP1rKW9a8o9mAjlVrf6GNPYmNvs1aZ5g9MH9wDSVc/0nzZ4MgeDl37SA0OZk8a46ZtXxUnmUhB3snufWgiXdFwk8sT98i5N0V8a4K7cvpU5AwZKukbgQL0U7RG9I+JskdjSp4WGlywPCG9BUOJTul9C8kgFxxiNJNa4dRnc6d6siA2KO8ZvQhpPSLZff3HKXegALIeGVdAYi2ZrYZNFquZ6QClBPYIFt6C6ox6NrZwbLPN93L4Spux/OaSM20LR/TPd4S9uc1Ot+kZjrE9KaKIooYY+EwnUouOWKGGdMg1inWtYWxo0efyxIwHY58t4r6XYxnTgKUkJcVhJSCno4wAY/iJs+j8oVqqleOoJuro+FBpJH407r8IEv+rBR9h8s+jIt0yXsxIfugj7l4ijZM0ASahva1DyDYJUNSIuDHTxnYC4a0hUoix+YXM1IqfefuMTdSC2ENQ4rzIRHXz4gHCsz7oW5gL9ZfRllwtPVlIBmhYLvc69z7Wc3vniYZi/Upz+YQTwEneFik6jwjIuyy/D+daw83g0/sVdScrIZlEm5fi0S+7XGINL18nR/cs=}
bot:
  automerge: true
